### ISSUE TITLE
Check type before casting in Equals method

### ISSUE THREAD

**Issue by KuroiRoy** [Unity-Technologies/Unity.Mathematics#184] opened 2020-12-03 13:08 UTC
I'm trying to serialize the int2 type with https://github.com/jilleJr/Newtonsoft.Json-for-Unity Unfortunately the serializer fails with an InvalidCastException because the int2 type has a very naive way of handling the equality members.
`public override bool Equals(object o) { return Equals((int2)o); }`

I've seen this issue in a forum thread here as well https://forum.unity.com/threads/unity-mathematics-serialization-float3.740336/

The reason this happens is that the JSON serializer checks for circular references by comparing with an object
`this._serializeStack.Contains<object>(value, this.Serializer._equalityComparer)`
Thus comparing the int2 with something that is clearly not an int2.

This can be solved very easily be changing all the Equals methods to something like this:
`public override bool Equals (object o) { return o is int2 && Equals((int2)o); }`

**Comment by unpacklo** [comment] 2020-12-03 18:26
This issue was fixed in #174 but hasn't been released yet. If you need this fixed ASAP, you should be able to download the latest package source from this git repo and use it in your own project. Let us know if you try this and have more problems.

**Closed by unpacklo** 2020-12-03 18:26 UTC

**Comment by KuroiRoy** [comment] 2020-12-04 08:57
Updating to the master branch fixes the issue. Thank you very much for letting me know!

**Comment by ArkTarusov** [comment] 2021-11-02 00:52
In version 1.2.4, the problem is again present, but with a different error.

`JsonSerializationException: Self referencing loop detected for property 'xxxx' with type 'Unity.Mathematics.int4'. Path 'test.xxxx'.`

```csh
	[Serializable]
	public class TestClass
	{
		public int2 test;
	}

	public class Tester
	{
		public void Run()
		{
			var tmp = new TestClass();
			tmp.test = new int2(1, 1);
			var json = JsonConvert.SerializeObject(tmp);
		}
	}
```

**Comment by unpacklo** [comment] 2021-11-02 22:49
@ArkTarusov can you post a full example that I can run? I'd like to fix this if Mathematics is causing problems here.

**Comment by ArkTarusov** [comment] 2021-11-07 16:38
@unpacklo Hi, Sorry for long answer. Didn't see notification.
There is already a complete example in my post) But here is the code with the method call. Just place this script somewhere on stage.
```cs
using System;
using Newtonsoft.Json;
using Unity.Mathematics;
using UnityEngine;

public class Test : MonoBehaviour
{
    private void Start()
    {
        Tester.Run();
    }
}

[Serializable]
public class TestClass
{
    public int2 test;
}

public static class Tester
{
    public static void Run()
    {
        var tmp = new TestClass();
        tmp.test = new int2(1, 1);
        var json = JsonConvert.SerializeObject(tmp);
        Debug.Log(json);
    }
}

````
New project, 2020.3.21f1. Update the math to 1.2.4. Run script.

result - 

> JsonSerializationException: Self referencing loop detected for property 'xxxx' with type 'Unity.Mathematics.int4'. Path 'test.xxxx'.
